language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - npm install --global codeclimate-test-reporter
script:
  - make check-coverage
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
